[package]
name = "ants"
version = "0.0.1"
edition = "2021"

[dependencies]
image = "0.23"
winit = "0.26"
cgmath = "0.18"
env_logger = "0.9"
log = "0.4"
wgpu = "0.12"
tokio = { version = "1", features = ["full"] }
bytemuck = { version = "1.7", features = [ "derive" ] }
anyhow = "1.0"
rand = "0.8.4"
